  #### general settings
  name: resnet14_1w4a_64ki_cifar10
  
  use_tb_logger: true
  model: CLSIRModel
  class_num: 100
  gpu_ids: [1]

  #### datasets
  datasets:
    train:
      name: CIFAR10
      mode: CIFAR10

      dataroot: ../../datasets/CLSDatasets/CIFAR10
      train: true
      download: true
      large: false

      use_shuffle: true
      workers_per_gpu: 16  # per GPU
      imgs_per_gpu: 128

    val:
      name: CIFAR10
      mode: CIFAR10

      dataroot: ../../datasets/CLSDatasets/CIFAR10
      train: false
      download: true
      large: false

      workers_per_gpu: 8
      imgs_per_gpu: 100

  #### network structures
  networks:
    netCLS:
      which_network: ResNet14_new_1w4a
      setting:
        num_classes: 10
      pretrain: 
        path: model_zoo/resnet14_fp32_64ki_cifar10_netCLS.pth
        strict_load: false

  #### training settings: learning rate scheme, loss
  train:
    resume_state: ~
    fmix: false

    losses:
      l_cls: 
        type: CrossEntropyLoss
        weight: 1.0

    optimizers:
      default:
        type: SGD
        lr: !!float 1e-2
        momentum: 0.9
        weight_decay: !!float 1e-4

      netCLS: ~

    train_mode: iter-base
    niter: 64000
    warmup_iter: -1  # no warm up

    schedulers:
      default:
        type: MultiStepRestartLR
        type: MultiStepRestartLR
        milestones: [32000, 48000]
        gamma: 0.1
    
    manual_seed: 0
    val_freq: !!float 4e3

  #### logger
  logger:
    print_freq: 100
    save_checkpoint_freq: !!float 4e3
